### ISSUE TITLE
Sync and Verify Upstream changes 

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/kubeflow#55]
The master branch is out of date with upstream kubeflow. Update the master and verify it doesn't break existing implementation of ODH notebook controller

Generated PR to sync upstream - https://github.com/opendatahub-io/kubeflow/pull/42

**Comment by shalberd** [comment]
Regarding [culling and istio dependency upstream](https://github.com/kubeflow/kubeflow/pull/6927), there seems to be something in-progress
There is also the question on how and where (upstream or downstream) to handle exclusion of image-field from notebook reconcile logic. I have put this [upstream as a PR](https://github.com/kubeflow/kubeflow/pull/6904), but it might be better to put this here downstream in opendatahub-io/kubeflow master branch. Especially since upstream folks do not seem too avid of it ...

**Comment by VaishnaviHire** [comment]
Just a note here, kubeflow 1.7 RC is [available](https://github.com/kubeflow/kubeflow/tree/v1.7.0-rc.1) for testing

**Comment by shalberd** [comment]
In our kubeflow master vs v1.6 branch, is there a particular reason why functions like createNotebookStatus and updateNotebookStatus are missing? See master branch https://github.com/opendatahub-io/kubeflow/blob/master/components/notebook-controller/controllers/notebook_controller.go see the https://github.com/kubeflow/kubeflow/pull/6628. Seems very siginificant to me.

**Comment by harshad16** [comment]
Related PR for this : https://github.com/openshift/release/pull/39704

**Comment by harshad16** [comment]
With setup of v1.7 branch 
this changes are done.
marking this issue as done.
